const base='https://shenoc-skinhealth.com';
const products=[
{name:'THE CREAM',slug:'the-cream',price:90,from:true,unit:'Größen im Shop auswählen',cat:'face',tag:'THE DAILY ESSENTIAL',sub:'Eine Creme. Dein tägliches Ritual.',img:'img_shenoc_home_teaser_cream.jpg',desc:'Universelle Gesichtspflege für jedes Alter und jeden Hauttyp. Mit SHÉNOC-Ceramid-Komplex, liposomal verkapselter Photolyase und reinem Aloe Vera. Unisex und unkompliziert.'},
{name:'INTENSE C',slug:'intense-c',price:140,unit:'30 ml · 466,67 € / 100 ml',cat:'serum',tag:'YOUR DAILY GLOW',sub:'Vitamin C für deine Pflegeroutine.',img:'img_home_shenoc_teaser_intensec.jpg',desc:'Das Vitamin-C-Serum der SHÉNOC Pflegelinie. Eine gezielte Ergänzung für alle, die sich einen frischen, strahlenden Teint wünschen.'},
{name:'BOOSTER',slug:'booster',price:170,unit:'30 ml · 566,67 € / 100 ml',cat:'serum',tag:'THE EXTRA STEP',sub:'Das Super-Serum.',img:'img_shenoc_home_teaser_booster-1.jpg',desc:'Intensive Serum-Pflege mit Tri-Hyaluron-Komplex und Himbeer-Stammzellenextrakt. Für eine Routine mit besonderem Fokus auf Feuchtigkeit.'},
{name:'EYE',slug:'eye',price:140,unit:'30 ml · 466,67 € / 100 ml',cat:'face',tag:'EYES ON YOU',sub:'Pflege für die Augenpartie.',img:'img_shenoc_home_teaser_eye.jpg',desc:'Gezielte Pflege für die Augenpartie mit Tri-Hyaluron-Komplex. Duftstofffrei formuliert und als Ergänzung deiner täglichen Gesichtspflege gedacht.'},
{name:'BODY',slug:'body',price:90,unit:'100 ml · 90,00 € / 100 ml',cat:'body',tag:'BEYOND THE FACE',sub:'Dein Pflegeritual für den Körper.',img:'img_shenoc_home_teaser_body-1_19c27564-7189-469d-b95e-dac344da93b0.jpg',desc:'Die SHÉNOC Philosophie für deinen Körper. Eine Körperpflege, die dein tägliches Ritual um ein sinnliches Pflegegefühl ergänzt.'},
{name:'CLEAN',slug:'clean',price:80,unit:'500 ml · 16,00 € / 100 ml',cat:'face',tag:'START FRESH',sub:'Milde Reinigung. Klarer Anfang.',img:'img_shenoc_home_teaser_clean.jpg',desc:'Milde Reinigung als erster Schritt deiner Pflegeroutine. Bereite deine Haut auf deine nachfolgenden SHÉNOC Essentials vor.'},
{name:'REPAIR',slug:'repair',price:50,unit:'10 ml · 500,00 € / 100 ml',cat:'face',tag:'A LITTLE EXTRA CARE',sub:'Gezielte Pflege für beanspruchte Haut.',img:'img_shenoc_home_teaser_repair.jpg',desc:'Die kompakte Spezialpflege der SHÉNOC Linie für beanspruchte Hautpartien. Ohne Duftstoffe. Anwendungshinweise findest du direkt im Shop.'},
{name:'LIP',slug:'lip',price:50,unit:'10 ml · 500,00 € / 100 ml',cat:'face',tag:'THE FINISHING TOUCH',sub:'Ein Pflegemoment für deine Lippen.',img:'img_shenoc_home_teaser_lip.jpg',desc:'Ausgewählte Inhaltsstoffe für die tägliche Lippenpflege. Das kleine Essential, das deine Routine überallhin begleitet.'},
{name:'SUN',slug:'sun',price:90,unit:'100 ml · 90,00 € / 100 ml',cat:'body',tag:'SONNENPFLEGE',sub:'Urlaub für deine Haut.',img:'img_shenoc_skin_health_shop_sun_3.jpg',desc:'Die duftstofffreie Sonnenpflege von SHÉNOC. Lichtschutzfaktor, Anwendung und aktuelle Verfügbarkeit bitte auf der Produktseite im Shop prüfen.'}
];
const ingredients=[['DIE BASIS: CERAMIDE NP & AP','Pflege beginnt mit Balance.','Der SHÉNOC-Ceramid-Komplex verbindet zwei Ceramide in einer durchdachten Formulierung. Entdecke die Inhaltsstoffe hinter THE CREAM und der SHÉNOC Pflegephilosophie.'],['DIREKT AUS DER PFLANZE','Natur. Sorgfältig ausgewählt.','SHÉNOC verwendet Aloe-Vera-Direktsaft aus kontrolliert biologischem Anbau. Gewonnen aus frischen, handgeschälten Blättern und schonend verarbeitet.'],['DAS ENZYM AUS MIKROALGEN','Ein besonderer Bestandteil.','Photolyase ist ein Enzym aus Mikroalgen und ein zentraler Bestandteil der SHÉNOC Formulierungen. Mehr zur Auswahl dieses Wirkstoffs und zur Markenphilosophie erfährst du im Wirkstoff-Lexikon.'],['DREI MOLEKÜLGRÖSSEN','Mehr Raum für Feuchtigkeit.','EYE und BOOSTER kombinieren drei unterschiedliche Hyaluronsäure-Molekülgrößen. Entdecke den Tri-Hyaluron-Komplex und die beiden Produkte für deine ergänzende Pflege.']];
const price=p=>(p.from?'ab ':'')+p.price.toLocaleString('de-DE')+' €';
const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const palettes=['#dad6e6','#eed9c6','#d4ddcc','#d2dfe4','#e6d4d1','#dae3d9','#ded8e6','#e8d0d4','#ece1c3'];
const tags=[['Unisex','Tägliche Pflege','Ceramide'],['Vitamin C','Serum','30 ml'],['Tri-Hyaluron','Serum','30 ml'],['Duftstofffrei','Augenpflege','30 ml'],['Körperpflege','100 ml'],['Reinigung','500 ml'],['Duftstofffrei','10 ml'],['Lippenpflege','10 ml'],['Duftstofffrei','Sonnenpflege']];
let activeFilter='all',stageIndex=0,routine=[],saved=false;
try{const value=JSON.parse(localStorage.getItem('shenoc-ritual-v3'));if(Array.isArray(value)&&value.length<=9&&value.every(i=>Number.isInteger(i)&&i>=0&&i<9)){routine=[...new Set(value)];saved=true}}catch{}
let toastTimer;function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3000)}
function announce(message){$('#live-status').textContent=message}
function renderProducts(filter=activeFilter){activeFilter=filter;const chosen=products.map((p,i)=>({...p,i})).filter(p=>filter==='all'||p.cat===filter);$('#product-grid').innerHTML=chosen.map(p=>`<article class="product-card" style="--card-bg:${palettes[p.i]}"><div class="product-image"><button class="product-visual" data-product="${p.i}" aria-label="${p.name} entdecken"><img src="assets/${p.img}" alt="SHÉNOC ${p.name}" loading="lazy" width="628" height="720" draggable="false"></button><span class="product-badge">${p.tag}</span><button class="product-plus ${routine.includes(p.i)?'selected':''}" data-toggle-product="${p.i}" aria-pressed="${routine.includes(p.i)}" aria-label="${p.name} ${routine.includes(p.i)?'aus Ritual entfernen':'zum Ritual hinzufügen'}">${routine.includes(p.i)?'✓':'+'}</button></div><div class="product-caption"><div><h3><button data-product="${p.i}">${p.name}</button></h3><p>${p.sub}</p></div><span class="product-price">${price(p)}</span></div><span class="unit">${p.unit}</span></article>`).join('');announce(chosen.length+' Produkte angezeigt')}
$$('[data-filter]').forEach(b=>b.addEventListener('click',()=>{$$('[data-filter]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b))});renderProducts(b.dataset.filter)}));
function updateAddButtons(){$$('[data-toggle-product]').forEach(b=>{const i=+b.dataset.toggleProduct,isIn=routine.includes(i);b.classList.toggle('selected',isIn);b.setAttribute('aria-pressed',String(isIn));b.setAttribute('aria-label',`${products[i].name} ${isIn?'aus Ritual entfernen':'zum Ritual hinzufügen'}`);b.textContent=b.classList.contains('product-plus')?(isIn?'✓':'+'):(isIn?'Entfernen':'Hinzufügen')});$('#stage-add').innerHTML=routine.includes(stageIndex)?'Im Ritual <span>✓</span>':'Zum Ritual hinzufügen <span>+</span>';$('#stage-add').setAttribute('aria-pressed',String(routine.includes(stageIndex)));const d=$('#detail-add');if(d){let i=+d.dataset.index;d.innerHTML=routine.includes(i)?'Aus Ritual entfernen <span>−</span>':'Zum Ritual hinzufügen <span>+</span>';d.setAttribute('aria-pressed',String(routine.includes(i)))}}
function renderRoutine(){try{localStorage.setItem('shenoc-ritual-v3',JSON.stringify(routine))}catch{};const shelf=$('#routine-shelf');shelf.innerHTML=routine.length?routine.map((i,n)=>`<div class="routine-item"><img src="assets/${products[i].img}" alt="" width="80" height="86"><button class="item-info" data-product="${i}" aria-label="${products[i].name} Details"><span class="step-label">DEIN ESSENTIAL / ${String(n+1).padStart(2,'0')}</span><h3>${products[i].name}</h3><span class="routine-item-price">${price(products[i])}</span></button><button class="remove" data-remove="${i}" aria-label="${products[i].name} entfernen">×</button></div>`).join(''):'<p class="routine-empty">Dein Warenkorb ist noch leer. Ergänze dein erstes Essential oder wähle einen Pflegefokus.</p>';const total=routine.reduce((s,i)=>s+products[i].price,0);$('#routine-total').textContent=(routine.some(i=>products[i].from)?'ab ':'')+total.toLocaleString('de-DE')+' €';$('#routine-count').textContent=$('#mobile-routine-count').textContent=String(routine.length).padStart(2,'0');$('#save-routine').innerHTML=(saved?'Auf diesem Gerät gemerkt':'Auf diesem Gerät merken')+' <span>'+(saved?'✓':'♡')+'</span>';$('#save-routine').disabled=!routine.length;$('#view-routine').disabled=!routine.length;updateAddButtons();announce(routine.length+' Essentials in deinem Ritual')}
function toggleProduct(i){if(!Number.isInteger(i)||!products[i])return;const had=routine.includes(i);routine=had?routine.filter(n=>n!==i):[...routine,i];saved=false;$$('[data-mode]').forEach(b=>{b.classList.remove('active');b.setAttribute('aria-pressed','false')});renderRoutine();toast(products[i].name+(had?' aus deinem Ritual entfernt.':' gehört jetzt zu deinem Ritual.'))}
const modes={base:[5,0],moisture:[5,2,0],glow:[5,1,0]};function setMode(mode){if(!modes[mode])return;routine=[...modes[mode]];saved=false;$$('[data-mode]').forEach(b=>{const selected=b.dataset.mode===mode;b.classList.toggle('active',selected);b.setAttribute('aria-pressed',String(selected))});renderRoutine();toast('Dein Ritual wurde angepasst.')}$$('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));
$('#save-routine').onclick=()=>{try{localStorage.setItem('shenoc-ritual-v3',JSON.stringify(routine));saved=true;renderRoutine();toast('Dein Ritual ist auf diesem Gerät gespeichert.')}catch{toast('Speichern ist hier nicht verfügbar. Deine Auswahl bleibt während dieses Besuchs erhalten.')}};
function renderStage(i,notify=true){stageIndex=(i+products.length)%products.length;const p=products[stageIndex];$('.experience').style.setProperty('--stage',palettes[stageIndex]);$('#stage-word').textContent=p.name.replace('THE ','');$('#stage-word').style.fontSize=p.name.length>8?'clamp(72px, 14vw, 230px)':'';$('#stage-image').src='assets/'+p.img;$('#stage-image').alt='SHÉNOC '+p.name;$('#stage-kicker').textContent=p.tag;$('#stage-title').textContent=p.name;$('#stage-description').textContent=p.sub;$('#stage-tags').innerHTML=tags[stageIndex].map(t=>`<span class="stage-tag">${t}</span>`).join('');$('#stage-price').textContent=price(p);$('#stage-counter').textContent=String(stageIndex+1).padStart(2,'0')+' — 09';$$('[data-stage]').forEach(b=>b.setAttribute('aria-pressed',String(+b.dataset.stage===stageIndex)));updateAddButtons();if(!reduced){$('#stage-image').animate([{opacity:.25,transform:'translateX(30px) rotate(7deg) scale(.94)'},{opacity:1,transform:'translateX(0) rotate(0) scale(1)'}],{duration:650,easing:'cubic-bezier(.2,.7,.2,1)'})}if(notify)announce(p.name+' ausgewählt, '+price(p))}
$('#stage-navigation').innerHTML=products.map((p,i)=>`<button data-stage="${i}" aria-pressed="${i===0}"><span>${String(i+1).padStart(2,'0')}</span>${p.name}</button>`).join('');$$('[data-stage]').forEach(b=>b.onclick=()=>renderStage(+b.dataset.stage));$('#stage-prev').onclick=()=>renderStage(stageIndex-1);$('#stage-next').onclick=()=>renderStage(stageIndex+1);$('#stage-add').onclick=()=>toggleProduct(stageIndex);$('#stage-detail').onclick=()=>openProduct(stageIndex);
const stage=$('#product-stage');let drag=null;stage.addEventListener('pointerdown',e=>{if(e.target.closest('button,a')||e.button!==0)return;drag={x:e.clientX,y:e.clientY,id:e.pointerId,dx:0,dy:0};stage.classList.add('dragging');stage.setPointerCapture(e.pointerId)});stage.addEventListener('pointermove',e=>{if(!drag)return;drag.dx=e.clientX-drag.x;drag.dy=e.clientY-drag.y;if(!reduced&&Math.abs(drag.dx)>Math.abs(drag.dy))$('.stage-art').style.transform=`translateX(${Math.max(-100,Math.min(100,drag.dx*.35))}px) rotate(${-8+drag.dx*.025}deg)`});function endDrag(e){if(!drag)return;if(Math.abs(drag.dx)>45&&Math.abs(drag.dx)>Math.abs(drag.dy)*1.3)renderStage(stageIndex+(drag.dx<0?1:-1));drag=null;stage.classList.remove('dragging');$('.stage-art').style.transform='';if(stage.hasPointerCapture(e.pointerId))stage.releasePointerCapture(e.pointerId)}stage.addEventListener('pointerup',endDrag);stage.addEventListener('pointercancel',e=>{drag=null;stage.classList.remove('dragging');$('.stage-art').style.transform=''});stage.addEventListener('keydown',e=>{if(e.target!==stage)return;if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();renderStage(stageIndex+(e.key==='ArrowRight'?1:-1))}});
const pd=$('#product-dialog'),qd=$('#quiz-dialog'),picker=$('#picker-dialog'),shop=$('#shop-dialog');function closeAll(){[pd,qd,picker,shop].forEach(d=>{if(d.open)d.close()})}
function openProduct(i){if(!products[i])return;const p=products[i];closeAll();$('#product-detail').innerHTML=`<div class="detail-layout"><div class="detail-image" style="--detail-bg:${palettes[i]}"><img src="assets/${p.img}" alt="SHÉNOC ${p.name}"></div><div class="detail-copy"><span class="eyebrow">${p.tag}</span><h2 id="product-title">${p.name}</h2><p>${p.desc}</p><p class="detail-origin">In Deutschland entwickelt und hergestellt.</p><p class="detail-price">${price(p)}<span class="unit">${p.unit}</span></p><button class="pill lavender" id="detail-add" data-index="${i}"></button><a class="pill ink" href="${base}/products/${p.slug}">Im SHÉNOC Shop ansehen</a><small>Inkl. MwSt., zzgl. Versand. Größen, vollständige Inhaltsstoffe und Bestellung im bestehenden SHÉNOC Shop.</small></div></div>`;$('#detail-add').onclick=()=>toggleProduct(i);updateAddButtons();pd.showModal()}
[pd,qd,picker,shop].forEach(d=>{d.querySelector('.close').onclick=()=>d.close();d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}})});
function openPicker(){$('#picker-items').innerHTML=products.map((p,i)=>`<div class="picker-item"><img src="assets/${p.img}" alt="" loading="lazy"><div><h3>${p.name}</h3><p>${price(p)}</p></div><button data-toggle-product="${i}" aria-pressed="${routine.includes(i)}"></button></div>`).join('');updateAddButtons();picker.showModal()}$('#routine-more').onclick=openPicker;
$('#view-routine').onclick=()=>{$('#shop-items').innerHTML=routine.map(i=>`<div class="shop-item"><img src="assets/${products[i].img}" alt=""><div><h3>${products[i].name}</h3><p>${price(products[i])}</p></div><a class="text-link" href="${base}/products/${products[i].slug}" target="_blank" rel="noopener">Zum Shop</a></div>`).join('');shop.showModal()};
document.addEventListener('click',e=>{const p=e.target.closest('[data-product]');if(p)openProduct(+p.dataset.product);const t=e.target.closest('[data-toggle-product]');if(t)toggleProduct(+t.dataset.toggleProduct);const r=e.target.closest('[data-remove]');if(r)toggleProduct(+r.dataset.remove)});
function selectIngredient(i){if(!ingredients[i])return;const d=ingredients[i];$$('[data-ingredient]').forEach((b,n)=>{b.setAttribute('aria-selected',String(n===i));b.tabIndex=n===i?0:-1});$('#ingredient-panel').setAttribute('aria-labelledby','ingredient-tab-'+i);$('#ingredient-kicker').textContent=d[0];$('#ingredient-title').textContent=d[1];$('#ingredient-text').textContent=d[2];if(!reduced)$('#ingredient-panel').animate([{opacity:.2,transform:'translateY(15px)'},{opacity:1,transform:'translateY(0)'}],{duration:400,easing:'ease-out'});$('#science-art').style.filter=['none','hue-rotate(70deg)','hue-rotate(-25deg)','hue-rotate(20deg)'][i]}
$$('[data-ingredient]').forEach(b=>{b.onclick=()=>selectIngredient(+b.dataset.ingredient);b.addEventListener('keydown',e=>{if(['ArrowDown','ArrowRight','ArrowUp','ArrowLeft','Home','End'].includes(e.key)){e.preventDefault();let i=e.key==='Home'?0:e.key==='End'?3:(+b.dataset.ingredient+(['ArrowRight','ArrowDown'].includes(e.key)?1:3))%4;selectIngredient(i);$('#ingredient-tab-'+i).focus()}})});
let step=0,answers=[],quizIds=[];const questions=[['Worauf liegt dein Fokus?',['Feuchtigkeit & Pflege','Ein frischer Teint','Eine einfache Basis']],['Wie viel Zeit gehört dir?',['Kurz & unkompliziert','Ein kleines Pflegeritual']],['Was möchtest du ergänzen?',['Meine Augenpflege','Meine Körperpflege','Ich bleibe beim Gesicht']]];
function renderQuiz(){const c=$('#quiz-content');if(step<3){c.innerHTML=`<span class="eyebrow">DEIN PFLEGERITUAL · ${step+1} / 3</span><div class="quiz-progress">${[0,1,2].map(i=>`<span class="${i<=step?'done':''}"></span>`).join('')}</div><h2 id="quiz-title" tabindex="-1">${questions[step][0]}</h2><div class="quiz-options">${questions[step][1].map((a,i)=>`<button data-answer="${i}">${a}<span>+</span></button>`).join('')}</div>${step?'<button class="quiz-back" data-back>Zurück</button>':''}`;}else{quizIds=[5,0];if(answers[1]===1&&answers[0]!==2)quizIds.splice(1,0,answers[0]===0?2:1);if(answers[2]!==2)quizIds.push(answers[2]===0?3:4);c.innerHTML=`<span class="eyebrow">DEIN RITUAL BEGINNT HIER</span><h2 id="quiz-title" tabindex="-1">Wenige Schritte.<br><em>Ganz für dich.</em></h2><p class="result-lead">Ausgewählt nach deinen Pflegewünschen.</p>${quizIds.map((i,n)=>`<button class="result-item" data-product="${i}"><img src="assets/${products[i].img}" alt=""><div><span class="eyebrow">ESSENTIAL ${n+1}</span><h3>${products[i].name}</h3><p>${products[i].sub}</p></div></button>`).join('')}<button class="pill ink result-apply" data-apply>Als mein Ritual übernehmen <span>+</span></button><p class="quiz-note">Diese Auswahl ist keine Hautanalyse oder medizinische Beratung. Prüfe bei Unverträglichkeiten bitte die Inhaltsstoffe und lass dich individuell beraten.</p><button class="quiz-back" data-restart>Noch einmal entdecken</button>`}if(qd.open)c.querySelector('#quiz-title').focus()}
$$('.quiz-open').forEach(b=>b.onclick=()=>{step=0;answers=[];renderQuiz();qd.showModal();$('#quiz-title').focus()});$('#quiz-content').addEventListener('click',e=>{const a=e.target.closest('[data-answer]');if(a){answers[step]=+a.dataset.answer;step++;renderQuiz()}if(e.target.closest('[data-back]')){step--;renderQuiz()}if(e.target.closest('[data-restart]')){step=0;answers=[];renderQuiz()}if(e.target.closest('[data-apply]')){routine=[...quizIds];saved=false;$$('[data-mode]').forEach(b=>{b.classList.remove('active');b.setAttribute('aria-pressed','false')});renderRoutine();qd.close();$('#routine').scrollIntoView({behavior:reduced?'instant':'smooth'});toast('Dein persönliches Ritual ist bereit.')}});
const reviews=[['„Schöne Konsistenz und toller Duft.“','S. Wagner · THE CREAM'],['„sehr gute Verträglichkeit, perfekte Konsistenz für einen Booster, schönes Hautbild“','Anonym · BOOSTER'],['„Erfrischt sofort nach dem auftragen. Super!“','Elke · EYE']];let reviewIndex=0;function showReview(){$('#review-quote').textContent=reviews[reviewIndex][0];$('#review-person').textContent=reviews[reviewIndex][1];$('#review-index').textContent=String(reviewIndex+1).padStart(2,'0')+' / 03';if(!reduced)$('#review-quote').animate([{opacity:0,transform:'translateY(12px)'},{opacity:1,transform:'translateY(0)'}],{duration:450})}$('#review-next').onclick=()=>{reviewIndex=(reviewIndex+1)%3;showReview()};$('#review-prev').onclick=()=>{reviewIndex=(reviewIndex+2)%3;showReview()};
const menu=$('.menu-trigger'),menuPanel=$('#menu-panel');function closeMenu(){menuPanel.hidden=true;document.body.classList.remove('menu-open');menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Menü öffnen')}menu.onclick=()=>{const open=menuPanel.hidden;menuPanel.hidden=!open;document.body.classList.toggle('menu-open',open);menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Menü schließen':'Menü öffnen');if(open)menuPanel.querySelector('a').focus()};menuPanel.querySelectorAll('a').forEach(a=>a.onclick=closeMenu);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!menuPanel.hidden){closeMenu();menu.focus()}if(e.key==='Tab'&&!menuPanel.hidden){const links=[menu,...menuPanel.querySelectorAll('a')];const first=links[0],last=links[links.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});
const video=$('#brand-video');let userPaused=reduced;function updateVideoButton(){const paused=video.paused;$('.film-symbol').textContent=paused?'▶':'Ⅱ';$('.film-label').textContent=paused?'FILM ANSEHEN':'FILM PAUSIEREN';$('#film-toggle').setAttribute('aria-label',paused?'Markenfilm abspielen':'Markenfilm pausieren')}$('#film-toggle').onclick=()=>{if(video.paused){userPaused=false;video.play().catch(()=>{toast('Der Film konnte nicht gestartet werden.');updateVideoButton()})}else{userPaused=true;video.pause()}};video.addEventListener('play',updateVideoButton);video.addEventListener('pause',updateVideoButton);video.addEventListener('error',()=>{video.style.opacity='0';$('.hero-media').style.background='url(assets/film-poster.jpg) center/cover';updateVideoButton()});if(!reduced&&!navigator.connection?.saveData)video.play().catch(updateVideoButton);else userPaused=true;
const videoObserver=new IntersectionObserver(entries=>{entries.forEach(e=>{if(!e.isIntersecting){video.pause()}else if(!userPaused&&!document.hidden){video.play().catch(updateVideoButton)}})},{threshold:.1});videoObserver.observe(video);document.addEventListener('visibilitychange',()=>{if(document.hidden)video.pause();else if(!userPaused&&$('.film-hero').getBoundingClientRect().bottom>0)video.play().catch(updateVideoButton)});
// Scroll-linked typography and restrained image movement. Native scrolling stays untouched.
const manifesto=$('#manifesto-text');manifesto.innerHTML=manifesto.innerHTML.replace(/([^<>]+)(?=<|$)/g,(text)=>text.trim()?text.replace(/([^\s]+)/g,'<span class="word">$1</span>'):text);const words=$$('.manifesto .word');const header=$('#header'),hero=$('.film-hero'),science=$('#science'),skin=$('.skin-break');let rafPending=false;
const dockLinks=$$('.mobile-dock>a');
let dockTarget=null,dockTimer;
function setDockActive(hash){dockLinks.forEach(a=>{const active=a.getAttribute('href')===hash;a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current')});$$('.routine-link').forEach(a=>{if(hash==='#routine')a.setAttribute('aria-current','location');else a.removeAttribute('aria-current')})}
function updateDock(){const rect=$('#routine').getBoundingClientRect();const line=Math.min(window.innerHeight*.35,240);if(dockTarget){const target=$(dockTarget).getBoundingClientRect();if(Math.abs(target.top-parseFloat(getComputedStyle(document.documentElement).scrollPaddingTop||'0'))<8){dockTarget=null;clearTimeout(dockTimer)}else return}setDockActive(rect.top<=line&&rect.bottom>line?'#routine':'#experience')}
document.addEventListener('click',e=>{const a=e.target.closest('a[href="#routine"],a[href="#experience"]');if(!a)return;dockTarget=a.getAttribute('href');setDockActive(dockTarget);clearTimeout(dockTimer);dockTimer=setTimeout(()=>{dockTarget=null;updateDock()},1800)});
function onScroll(){updateDock();rafPending=false;const y=window.scrollY,h=window.innerHeight,full=document.documentElement.scrollHeight-h;$('.scroll-progress').style.transform=`scaleX(${full>0?y/full:0})`;header.classList.toggle('scrolled',y>40);if(reduced)return;const r=$('#manifesto').getBoundingClientRect();const progress=Math.max(0,Math.min(1,(h-r.top)/(h+r.height*.22)));words.forEach((word,i)=>word.classList.toggle('lit',progress>(i+.3)/words.length));if(hero.getBoundingClientRect().bottom>0){video.style.transform=`scale(1.04) translateY(${Math.min(y*.15,110)}px)`;$('.hero-title').style.transform=`translateY(${Math.min(y*.1,75)}px)`}const sr=science.getBoundingClientRect();if(sr.top<h&&sr.bottom>0)$('#science-art').style.transform=`scale(1.09) translateY(${(sr.top-h/2)*.025}px)`;const sk=skin.getBoundingClientRect();if(sk.top<h&&sk.bottom>0)skin.querySelector('img').style.transform=`translateY(${(sk.top-h/2)*.07}px)`}
window.addEventListener('scroll',()=>{if(!rafPending){rafPending=true;requestAnimationFrame(onScroll)}},{passive:true});window.addEventListener('resize',()=>requestAnimationFrame(onScroll));
if(!reduced){document.body.classList.add('motion-ready');const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');obs.unobserve(e.target)}}),{threshold:.09});$$('.reveal').forEach(el=>obs.observe(el));if(matchMedia('(pointer:fine)').matches){const cursor=$('.drag-cursor');stage.addEventListener('pointermove',e=>{if(e.pointerType!=='mouse')return;const rect=stage.getBoundingClientRect();cursor.style.display='flex';cursor.style.left=(e.clientX-rect.left)+'px';cursor.style.top=(e.clientY-rect.top)+'px';cursor.style.opacity=e.target.closest('button,a,.stage-left,.stage-right')?'0':'1';if(!drag&&!e.target.closest('button,a,.stage-left,.stage-right'))$('.stage-art').style.transform=`rotate(${-8+(e.clientX-rect.left-rect.width/2)*.007}deg) translateY(${(e.clientY-rect.top-rect.height/2)*.02}px)`});stage.addEventListener('pointerleave',()=>{cursor.style.opacity='0';if(!drag)$('.stage-art').style.transform=''})}}
renderProducts();renderStage(0,false);renderRoutine();if(saved){$$('[data-mode]').forEach(b=>{const selected=JSON.stringify(modes[b.dataset.mode])===JSON.stringify(routine);b.classList.toggle('active',selected);b.setAttribute('aria-pressed',String(selected))})}selectIngredient(0);showReview();onScroll();
// These optional browser tools operate on the same visible controls and local ritual.
if(document.modelContext?.registerTool){const controller=new AbortController();const registrations=[{name:'list_shenoc_essentials',description:'List SHÉNOC products and the current on-page ritual. No purchase is made.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({products:products.map((p,i)=>({id:i,name:p.name,price:p.price,from:!!p.from})),ritual:[...routine]})},{name:'set_shenoc_ritual',description:'Replace the visible local ritual with selected product IDs. Does not purchase or save to device.',inputSchema:{type:'object',properties:{productIds:{type:'array',items:{type:'integer',minimum:0,maximum:8},maxItems:9,uniqueItems:true}},required:['productIds'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!input||!Array.isArray(input.productIds)||input.productIds.length>9||input.productIds.some(i=>!Number.isInteger(i)||!products[i])||new Set(input.productIds).size!==input.productIds.length)throw new Error('Provide unique product IDs from 0 to 8.');routine=[...input.productIds];saved=false;$$('[data-mode]').forEach(b=>{b.classList.remove('active');b.setAttribute('aria-pressed','false')});renderRoutine();return{ritual:products.filter((_,i)=>routine.includes(i)).map(p=>p.name),purchaseMade:false}}}];for(const tool of registrations){try{Promise.resolve(document.modelContext.registerTool(tool,{signal:controller.signal})).catch(()=>{})}catch{}}window.addEventListener('pagehide',()=>controller.abort(),{once:true})}
